### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by TechStudent10** [KendallDoesCoding/tap-for-a-surprise#2]
But I must say, gg

**Comment by TechStudent11** [comment]
haha number 1 you haven't configured the bot but that doesn't matter because second, I closed the issue so fast that the bot didn't have time to comment. sheesh

**Comment by KendallDoesCoding** [comment]
> haha number 1 you haven't configured the bot but that doesn't matter because second, I closed the issue so fast that the bot didn't have time to comment. sheesh

LOL, thanks,

**Comment by KendallDoesCoding** [comment]
> But I must say, gg

You didn't win a prize sed.
