### ISSUE TITLE
[DOCS] Add CONTRIBUTING GUIDELINES

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/tap-for-a-surprise#4]
Add Contributing Guidelines like:
[Example in other repo ](https://github.com/KendallDoesCoding/mogul-christmas/blob/main/.github/CONTRIBUTING.md)

**Comment by frazie** [comment]
Hello,
I'd like to handle this issue

can it be assigned to me?

**Comment by KendallDoesCoding** [comment]
> Hello, I'd like to handle this issue
> 
> can it be assigned to me?

Sure!

**Comment by frazie** [comment]
Also, is a contributing template allowed for the project?

**Comment by KendallDoesCoding** [comment]
> Also, is a contributing template allowed for the project?

Sorry, I didn't get you. What is a contributing template?

**Comment by frazie** [comment]
> > Also, is a contributing template allowed for the project?
> 
> Sorry, I didn't get you. What is a contributing template?

I meant if it was okay to use a template for the contributing guidelines...but I believe I will know in a few

**Comment by KendallDoesCoding** [comment]
> > > Also, is a contributing template allowed for the project?
> > 
> > 
> > Sorry, I didn't get you. What is a contributing template?
> 
> I meant if it was okay to use a template for the contributing guidelines...but I believe I will know in a few

yeah, there's no issues using a template!
