### ISSUE TITLE
Improve design/interface.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/tap-for-a-surprise#7]
The website looks kinda ugly rn, the design requires to be changed to look nice and believable, because this is a real product and people can actually win the prizes mentioned, no scam :)

**Comment by thng17** [comment]
Hello @KendallDoesCoding I would like to help u. I saw in ur projekt that u doesn't use any frontend frameworks. How about using bootatrap? I can do a prototype on Figma for the first page (and send the link here)? I can also implement it afterwards. :)

**Comment by thng17** [comment]
here my idea as wireframe: https://www.figma.com/file/fqUoAESndFufBKU5IpOR6Q/tap-for-suprice?node-id=0%3A1

**Comment by KendallDoesCoding** [comment]
> here my idea as wireframe: https://www.figma.com/file/fqUoAESndFufBKU5IpOR6Q/tap-for-suprice?node-id=0%3A1

Looks amazing, thanks! Can you implement this, will assign you if yes.

**Comment by thng17** [comment]
sure I would love to :)

**Comment by KendallDoesCoding** [comment]
> sure I would love to :)

thanks
